# TODO

# N64_CFLAGS += -isystem $(SOURCE_DIR)/libs/libjpeg-turbo -isystem $(SOURCE_DIR)/libs/libjpeg-turbo-src

# SRCS = \
# 	libs/libjpeg-turbo/jaricom.c \
# 	libs/libjpeg-turbo/jcomapi.c \
# 	libs/libjpeg-turbo/jdapimin.c \
# 	libs/libjpeg-turbo/jdapistd.c \
# 	libs/libjpeg-turbo/jdarith.c \
# 	libs/libjpeg-turbo/jdatasrc.c \
# 	libs/libjpeg-turbo/jdcoefct.c \
# 	libs/libjpeg-turbo/jdcolor.c \
# 	libs/libjpeg-turbo/jddctmgr.c \
# 	libs/libjpeg-turbo/jdhuff.c \
# 	libs/libjpeg-turbo/jdinput.c \
# 	libs/libjpeg-turbo/jdmainct.c \
# 	libs/libjpeg-turbo/jdmarker.c \
# 	libs/libjpeg-turbo/jdmaster.c \
# 	libs/libjpeg-turbo/jdmerge.c \
# 	libs/libjpeg-turbo/jdpostct.c \
# 	libs/libjpeg-turbo/jdsample.c \
# 	libs/libjpeg-turbo/jerror.c \
# 	libs/libjpeg-turbo/jidctflt.c \
# 	libs/libjpeg-turbo/jidctfst.c \
# 	libs/libjpeg-turbo/jidctint.c \
# 	libs/libjpeg-turbo/jmemmgr.c \
# 	libs/libjpeg-turbo/jmemnobs.c \
# 	libs/libjpeg-turbo/jquant1.c \
# 	libs/libjpeg-turbo/jquant2.c \
# 	libs/libjpeg-turbo/jutils.c \
# 	libs/libjpeg-turbo/jdphuff.c \
# 	libs/libjpeg-turbo/jidctred.c \
# 	libs/libjpeg-turbo/jsimd_none.c
