name: Bug report
description: Create a bug report to help us improve
labels:
  - "bug"
  - "awaiting triage"
body:
  - type: markdown
    attributes:
      value: |
        # :warning: **Please read before raising the issue** :warning:

        If you have a **question** that needs clarification on something, or need help in a particular situation, **DO NOT** open an issue here, create a discussion instead. _Otherwise it will be automatically closed!_ .

        Please make sure to provide as much information as possible. 
        Failing to do so will most likely end up on the issue being closed without discussion. Don't take offense at this, 
        whenever an issue is raised without following the template and/or adding the required information, too much time has to be spent going back and forth to obtain the details that are outlined below.

  - type: input
    id: flashcart_firmware_version
    attributes:
      label: Firmware version of the flashcart
      description: Press (Start) button on the menu, then (Check Flashcart Information).
      placeholder: V2.20.2, N/A
    validations:
      required: true

  - type: input
    id: menu_version
    attributes:
      label: N64 Flashcart Menu revision used
      description: Press (Start) button on the menu, then (Check Menu Information), or specify github download URL.
      placeholder: e.g 1.2.3.456, N/A
    validations:
      required: true

  - type: input
    id: n64_region
    attributes:
      label: N64 console region
      description: PAL, NTSC-U, NTSC-J, MPAL, etc.
      placeholder: NTSC
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: How to reproduce
      description: Detailed repro steps so we can see the same problem. If not already explained above.
      placeholder: |
        1.
        2.
        ...
    validations:
      required: false

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. If applicable.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Very helpful if you send along a few screenshots to help visualize the issue!
      placeholder: drag and drop here, if applicable
    validations:
      required: false

  - type: textarea
    id: configuration_file
    attributes:
      label: configuration file(s)
      description: The text of the configuration file(s) used. If applicable.
      placeholder: |
        for example paste the content of the configuration file (config.ini) here.
    validations:
      required: false

  - type: textarea
    id: other_things
    attributes:
      label: Additional information
      description: Other suggested things. If applicable/relevant.
      placeholder: |
        for example link to the repository with sample code
        code snippets
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Make an effort to fix the bug
        
        Attempt to submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.
