FROM debian:trixie-slim

# Minimal image: install only what's needed for building and the project's toolchain
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential doxygen git python3 wget nodejs npm

# Install dotNet tools
RUN wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && \
    chmod +x ./dotnet-install.sh && \
    ./dotnet-install.sh --channel LTS && \
    rm dotnet-install.sh

# Configure environment variables so the system can find dotnet
ENV DOTNET_ROOT=/root/.dotnet
ENV PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

# Install system dependencies required by Playwright/Chromium
# Automatically install all missing system dependencies for browsers
RUN npx playwright install-deps

# Install libdragon toolchain (packaged .deb)
RUN wget https://github.com/DragonMinded/libdragon/releases/download/toolchain-continuous-prerelease/gcc-toolchain-mips64-x86_64.deb && \
    dpkg -i gcc-toolchain-mips64-x86_64.deb && \
    rm gcc-toolchain-mips64-x86_64.deb

# Environment Config
RUN git config --global --add safe.directory "*" && \
    SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" && \
    echo "$SNIPPET" >> "/root/.bashrc"
