name: build documentation

on:
  push:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1 # we only require the last check-in, unless we want to create a changelog.

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@1.9.5
        with:
          working-directory: 'src/'
          doxyfile-path: 'doxygen.conf'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
